spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Creator8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true